export interface PopeRecord {
  num: number;
  nameVi: string;
  nameLatin: string;
  reign: string;
  birthPlace?: string;
  notes?: string;
  imageUrl?: string;
}

// Danh sách biên niên sử 266 Vị Giáo Hoàng của Giáo Hội Công Giáo Rôma (Từ Thánh Phêrô đến ĐTC Phanxicô)
export const ALL_POPES: PopeRecord[] = [
  { num: 1, nameVi: 'Thánh Phêrô', nameLatin: 'Petrus', reign: '33 – 67', birthPlace: 'Bethsaida, Galilee', notes: 'Tông đồ trưởng, được Chúa Giêsu trao chìa khóa Nước Trời (Mt 16,18).' },
  { num: 2, nameVi: 'Thánh Linô', nameLatin: 'Linus', reign: '67 – 76', birthPlace: 'Volterra, Italia' },
  { num: 3, nameVi: 'Thánh Anaclêtô (Clêtô)', nameLatin: 'Anacletus / Cletus', reign: '76 – 88', birthPlace: 'Roma' },
  { num: 4, nameVi: 'Thánh Clêmentê I', nameLatin: 'Clemens I', reign: '88 – 97', birthPlace: 'Roma', notes: 'Tác giả bức thư gửi giáo đoàn Côrintô nổi tiếng.' },
  { num: 5, nameVi: 'Thánh Êvaristô', nameLatin: 'Evaristus', reign: '97 – 105', birthPlace: 'Bethlehem, Judea' },
  { num: 6, nameVi: 'Thánh Alêxandê I', nameLatin: 'Alexander I', reign: '105 – 115', birthPlace: 'Roma' },
  { num: 7, nameVi: 'Thánh Xíttô I', nameLatin: 'Sixtus I', reign: '115 – 125', birthPlace: 'Roma' },
  { num: 8, nameVi: 'Thánh Têlêphorô', nameLatin: 'Telesphorus', reign: '125 – 136', birthPlace: 'Hy Lạp' },
  { num: 9, nameVi: 'Thánh Hyginô', nameLatin: 'Hyginus', reign: '136 – 140', birthPlace: 'Athens, Hy Lạp' },
  { num: 10, nameVi: 'Thánh Piô I', nameLatin: 'Pius I', reign: '140 – 155', birthPlace: 'Aquileia, Italia' },
  { num: 11, nameVi: 'Thánh Anicêtô', nameLatin: 'Anicetus', reign: '155 – 166', birthPlace: 'Emesa, Syria' },
  { num: 12, nameVi: 'Thánh Sôtêrô', nameLatin: 'Soterius', reign: '166 – 175', birthPlace: 'Fondi, Italia' },
  { num: 13, nameVi: 'Thánh Êlêuthêriô', nameLatin: 'Eleutherius', reign: '175 – 189', birthPlace: 'Nicopolis, Hy Lạp' },
  { num: 14, nameVi: 'Thánh Victor I', nameLatin: 'Victor I', reign: '189 – 199', birthPlace: 'Bắc Phi' },
  { num: 15, nameVi: 'Thánh Zêphyrinô', nameLatin: 'Zephyrinus', reign: '199 – 217', birthPlace: 'Roma' },
  { num: 16, nameVi: 'Thánh Callistô I', nameLatin: 'Callistus I', reign: '217 – 222', birthPlace: 'Roma' },
  { num: 17, nameVi: 'Thánh Urbanô I', nameLatin: 'Urbanus I', reign: '222 – 230', birthPlace: 'Roma' },
  { num: 18, nameVi: 'Thánh Pôntianô', nameLatin: 'Pontianus', reign: '230 – 235', birthPlace: 'Roma' },
  { num: 19, nameVi: 'Thánh Antêrô', nameLatin: 'Anterus', reign: '235 – 236', birthPlace: 'Petilia Policastro, Hy Lạp' },
  { num: 20, nameVi: 'Thánh Fabianô', nameLatin: 'Fabianus', reign: '236 – 250', birthPlace: 'Roma' },
  { num: 21, nameVi: 'Thánh Cornêliô', nameLatin: 'Cornelius', reign: '251 – 253', birthPlace: 'Roma' },
  { num: 22, nameVi: 'Thánh Luciô I', nameLatin: 'Lucius I', reign: '253 – 254', birthPlace: 'Roma' },
  { num: 23, nameVi: 'Thánh Stêphanô I', nameLatin: 'Stephanus I', reign: '254 – 257', birthPlace: 'Roma' },
  { num: 24, nameVi: 'Thánh Xíttô II', nameLatin: 'Sixtus II', reign: '257 – 258', birthPlace: 'Hy Lạp' },
  { num: 25, nameVi: 'Thánh Điônysiô', nameLatin: 'Dionysius', reign: '259 – 268', birthPlace: 'Hy Lạp' },
  { num: 26, nameVi: 'Thánh Phêlích I', nameLatin: 'Felix I', reign: '269 – 274', birthPlace: 'Roma' },
  { num: 27, nameVi: 'Thánh Êutychianô', nameLatin: 'Eutychianus', reign: '275 – 283', birthPlace: 'Luni, Italia' },
  { num: 28, nameVi: 'Thánh Caiô', nameLatin: 'Caius', reign: '283 – 296', birthPlace: 'Salona, Dalmatia' },
  { num: 29, nameVi: 'Thánh Marcelinô', nameLatin: 'Marcellinus', reign: '296 – 304', birthPlace: 'Roma' },
  { num: 30, nameVi: 'Thánh Marcellô I', nameLatin: 'Marcellus I', reign: '308 – 309', birthPlace: 'Roma' },
  { num: 31, nameVi: 'Thánh Eusebiô', nameLatin: 'Eusebius', reign: '309 – 310', birthPlace: 'Sardinia' },
  { num: 32, nameVi: 'Thánh Miltiadê', nameLatin: 'Miltiades', reign: '311 – 314', birthPlace: 'Bắc Phi' },
  { num: 33, nameVi: 'Thánh Sylvêstrô I', nameLatin: 'Silvester I', reign: '314 – 335', birthPlace: 'Roma', notes: 'Thời kỳ Hoàng đế Constantinô và Công đồng Nicaea I (325).' },
  { num: 34, nameVi: 'Thánh Marcô', nameLatin: 'Marcus', reign: '336', birthPlace: 'Roma' },
  { num: 35, nameVi: 'Thánh Giuliô I', nameLatin: 'Iulius I', reign: '337 – 352', birthPlace: 'Roma' },
  { num: 36, nameVi: 'Đức Libêriô', nameLatin: 'Liberius', reign: '352 – 366', birthPlace: 'Roma' },
  { num: 37, nameVi: 'Thánh Đamasô I', nameLatin: 'Damasus I', reign: '366 – 384', birthPlace: 'Idanha-a-Velha, Bồ Đào Nha', notes: 'Ủy thác Thánh Giêrônimô dịch bản Kinh Thánh Vulgate Latinh.' },
  { num: 38, nameVi: 'Thánh Siriciô', nameLatin: 'Siricius', reign: '384 – 399', birthPlace: 'Roma' },
  { num: 39, nameVi: 'Thánh Anastasiô I', nameLatin: 'Anastasius I', reign: '399 – 401', birthPlace: 'Roma' },
  { num: 40, nameVi: 'Thánh Innocentê I', nameLatin: 'Innocentius I', reign: '401 – 417', birthPlace: 'Albano, Italia' },
  { num: 41, nameVi: 'Thánh Zôsimô', nameLatin: 'Zosimus', reign: '417 – 418', birthPlace: 'Mesoraca, Calabria' },
  { num: 42, nameVi: 'Thánh Bônifaciô I', nameLatin: 'Bonifacius I', reign: '418 – 422', birthPlace: 'Roma' },
  { num: 43, nameVi: 'Thánh Cêlestinô I', nameLatin: 'Caelestinus I', reign: '422 – 432', birthPlace: 'Campania, Italia' },
  { num: 44, nameVi: 'Thánh Xíttô III', nameLatin: 'Sixtus III', reign: '432 – 440', birthPlace: 'Roma' },
  { num: 45, nameVi: 'Thánh Lêô Cả (Lêô I)', nameLatin: 'Leo I (Magnus)', reign: '440 – 461', birthPlace: 'Tuscany, Italia', notes: 'Tiến sĩ Hội Thánh, bảo vệ niềm tin hai bản tính của Chúa Kitô tại Công đồng Chalcedon (451).' },
  { num: 46, nameVi: 'Thánh Hilariô', nameLatin: 'Hilarius', reign: '461 – 468', birthPlace: 'Sardinia' },
  { num: 47, nameVi: 'Thánh Simpliciô', nameLatin: 'Simplicius', reign: '468 – 483', birthPlace: 'Tivoli, Italia' },
  { num: 48, nameVi: 'Thánh Phêlích III', nameLatin: 'Felix III', reign: '483 – 492', birthPlace: 'Roma' },
  { num: 49, nameVi: 'Thánh Gêlasiô I', nameLatin: 'Gelasius I', reign: '492 – 496', birthPlace: 'Bắc Phi' },
  { num: 50, nameVi: 'Đức Anastasiô II', nameLatin: 'Anastasius II', reign: '496 – 498', birthPlace: 'Roma' },
  { num: 51, nameVi: 'Thánh Symmachô', nameLatin: 'Symmachus', reign: '498 – 514', birthPlace: 'Sardinia' },
  { num: 52, nameVi: 'Thánh Hôrmisđa', nameLatin: 'Hormisdas', reign: '514 – 523', birthPlace: 'Frosinone, Italia' },
  { num: 53, nameVi: 'Thánh Gioan I', nameLatin: 'Ioannes I', reign: '523 – 526', birthPlace: 'Siena, Italia' },
  { num: 54, nameVi: 'Thánh Phêlích IV', nameLatin: 'Felix IV', reign: '526 – 530', birthPlace: 'Samnium, Italia' },
  { num: 55, nameVi: 'Đức Bônifaciô II', nameLatin: 'Bonifacius II', reign: '530 – 532', birthPlace: 'Roma (Gốc Ostrogoth)' },
  { num: 56, nameVi: 'Đức Gioan II', nameLatin: 'Ioannes II', reign: '533 – 535', birthPlace: 'Roma', notes: 'Vị đầu tiên đổi tên khi lên ngôi Giáo hoàng (tên thật Mercurius).' },
  { num: 57, nameVi: 'Thánh Agapêtô I', nameLatin: 'Agapetus I', reign: '535 – 536', birthPlace: 'Roma' },
  { num: 58, nameVi: 'Thánh Silvêriô', nameLatin: 'Silverius', reign: '536 – 537', birthPlace: 'Frosinone, Italia' },
  { num: 59, nameVi: 'Đức Vigiliô', nameLatin: 'Vigilius', reign: '537 – 555', birthPlace: 'Roma' },
  { num: 60, nameVi: 'Đức Pêlagiô I', nameLatin: 'Pelagius I', reign: '556 – 561', birthPlace: 'Roma' },
  { num: 61, nameVi: 'Đức Gioan III', nameLatin: 'Ioannes III', reign: '561 – 574', birthPlace: 'Roma' },
  { num: 62, nameVi: 'Đức Bênêđictô I', nameLatin: 'Benedictus I', reign: '575 – 579', birthPlace: 'Roma' },
  { num: 63, nameVi: 'Đức Pêlagiô II', nameLatin: 'Pelagius II', reign: '579 – 590', birthPlace: 'Roma (Gốc Ostrogoth)' },
  { num: 64, nameVi: 'Thánh Grêgôriô Cả (Grêgôriô I)', nameLatin: 'Gregorius I (Magnus)', reign: '590 – 604', birthPlace: 'Roma', notes: 'Tiến sĩ Hội Thánh, cải cách phụng vụ, nguồn gốc Bình ca Grêgôrianô.' },
  { num: 65, nameVi: 'Đức Sabinianô', nameLatin: 'Sabinianus', reign: '604 – 606', birthPlace: 'Blera, Italia' },
  { num: 66, nameVi: 'Đức Bônifaciô III', nameLatin: 'Bonifacius III', reign: '607', birthPlace: 'Roma' },
  { num: 67, nameVi: 'Thánh Bônifaciô IV', nameLatin: 'Bonifacius IV', reign: '608 – 615', birthPlace: 'Abruzzo, Italia' },
  { num: 68, nameVi: 'Thánh Ađêôđatô I (Đêôđatô I)', nameLatin: 'Adeodatus I', reign: '615 – 618', birthPlace: 'Roma' },
  { num: 69, nameVi: 'Đức Bônifaciô V', nameLatin: 'Bonifacius V', reign: '619 – 625', birthPlace: 'Napoli, Italia' },
  { num: 70, nameVi: 'Đức Hônôriô I', nameLatin: 'Honorius I', reign: '625 – 638', birthPlace: 'Campania, Italia' },
  { num: 71, nameVi: 'Đức Sêvêrinô', nameLatin: 'Severinus', reign: '640', birthPlace: 'Roma' },
  { num: 72, nameVi: 'Đức Gioan IV', nameLatin: 'Ioannes IV', reign: '640 – 642', birthPlace: 'Zadar, Dalmatia' },
  { num: 73, nameVi: 'Đức Thêôđôrô I', nameLatin: 'Theodorus I', reign: '642 – 649', birthPlace: 'Jerusalem' },
  { num: 74, nameVi: 'Thánh Martinô I', nameLatin: 'Martinus I', reign: '649 – 655', birthPlace: 'Todi, Umbria' },
  { num: 75, nameVi: 'Thánh Eugêniô I', nameLatin: 'Eugenius I', reign: '654 – 657', birthPlace: 'Roma' },
  { num: 76, nameVi: 'Thánh Vitalianô', nameLatin: 'Vitalianus', reign: '657 – 672', birthPlace: 'Segni, Italia' },
  { num: 77, nameVi: 'Đức Ađêôđatô II', nameLatin: 'Adeodatus II', reign: '672 – 676', birthPlace: 'Roma' },
  { num: 78, nameVi: 'Đức Đônô', nameLatin: 'Donus', reign: '676 – 678', birthPlace: 'Roma' },
  { num: 79, nameVi: 'Thánh Agathô', nameLatin: 'Agatho', reign: '678 – 681', birthPlace: 'Sicilia' },
  { num: 80, nameVi: 'Thánh Lêô II', nameLatin: 'Leo II', reign: '682 – 683', birthPlace: 'Sicilia' },
  { num: 81, nameVi: 'Thánh Bênêđictô II', nameLatin: 'Benedictus II', reign: '684 – 685', birthPlace: 'Roma' },
  { num: 82, nameVi: 'Đức Gioan V', nameLatin: 'Ioannes V', reign: '685 – 686', birthPlace: 'Antioch, Syria' },
  { num: 83, nameVi: 'Đức Cônôn', nameLatin: 'Conon', reign: '686 – 687', birthPlace: 'Sicilia / Thrace' },
  { num: 84, nameVi: 'Thánh Sêrgiô I', nameLatin: 'Sergius I', reign: '687 – 701', birthPlace: 'Palermo, Sicilia' },
  { num: 85, nameVi: 'Đức Gioan VI', nameLatin: 'Ioannes VI', reign: '701 – 705', birthPlace: 'Hy Lạp' },
  { num: 86, nameVi: 'Đức Gioan VII', nameLatin: 'Ioannes VII', reign: '705 – 707', birthPlace: 'Rossano, Calabria' },
  { num: 87, nameVi: 'Đức Sisinniô', nameLatin: 'Sisinnius', reign: '708', birthPlace: 'Syria' },
  { num: 88, nameVi: 'Đức Constantinô', nameLatin: 'Constantinus', reign: '708 – 715', birthPlace: 'Syria' },
  { num: 89, nameVi: 'Thánh Grêgôriô II', nameLatin: 'Gregorius II', reign: '715 – 731', birthPlace: 'Roma' },
  { num: 90, nameVi: 'Thánh Grêgôriô III', nameLatin: 'Gregorius III', reign: '731 – 741', birthPlace: 'Syria' },
  { num: 91, nameVi: 'Thánh Zacaria', nameLatin: 'Zacharias', reign: '741 – 752', birthPlace: 'Santa Severina, Calabria' },
  { num: 92, nameVi: 'Đức Stêphanô II', nameLatin: 'Stephanus II', reign: '752 – 757', birthPlace: 'Roma' },
  { num: 93, nameVi: 'Thánh Phaolô I', nameLatin: 'Paulus I', reign: '757 – 767', birthPlace: 'Roma' },
  { num: 94, nameVi: 'Đức Stêphanô III', nameLatin: 'Stephanus III', reign: '768 – 772', birthPlace: 'Siracusa, Sicilia' },
  { num: 95, nameVi: 'Đức Hađrianô I', nameLatin: 'Hadrianus I', reign: '772 – 795', birthPlace: 'Roma' },
  { num: 96, nameVi: 'Thánh Lêô III', nameLatin: 'Leo III', reign: '795 – 816', birthPlace: 'Roma', notes: 'Tấn phong Hoàng đế Charlemagne năm 800.' },
  { num: 97, nameVi: 'Đức Stêphanô IV', nameLatin: 'Stephanus IV', reign: '816 – 817', birthPlace: 'Roma' },
  { num: 98, nameVi: 'Thánh Paschal I', nameLatin: 'Paschalis I', reign: '817 – 824', birthPlace: 'Roma' },
  { num: 99, nameVi: 'Đức Eugêniô II', nameLatin: 'Eugenius II', reign: '824 – 827', birthPlace: 'Roma' },
  { num: 100, nameVi: 'Đức Valentinô', nameLatin: 'Valentinus', reign: '827', birthPlace: 'Roma' },
  { num: 101, nameVi: 'Đức Grêgôriô IV', nameLatin: 'Gregorius IV', reign: '827 – 844', birthPlace: 'Roma' },
  { num: 102, nameVi: 'Đức Sêrgiô II', nameLatin: 'Sergius II', reign: '844 – 847', birthPlace: 'Roma' },
  { num: 103, nameVi: 'Thánh Lêô IV', nameLatin: 'Leo IV', reign: '847 – 855', birthPlace: 'Roma', notes: 'Xây dựng Bức tường thành Leonine quanh Vatican.' },
  { num: 104, nameVi: 'Đức Bênêđictô III', nameLatin: 'Benedictus III', reign: '855 – 858', birthPlace: 'Roma' },
  { num: 105, nameVi: 'Thánh Nicôla Cả (Nicôla I)', nameLatin: 'Nicolaus I (Magnus)', reign: '858 – 867', birthPlace: 'Roma' },
  { num: 106, nameVi: 'Đức Hađrianô II', nameLatin: 'Hadrianus II', reign: '867 – 872', birthPlace: 'Roma' },
  { num: 107, nameVi: 'Đức Gioan VIII', nameLatin: 'Ioannes VIII', reign: '872 – 882', birthPlace: 'Roma' },
  { num: 108, nameVi: 'Đức Marinô I', nameLatin: 'Marinus I', reign: '882 – 884', birthPlace: 'Gallese, Italia' },
  { num: 109, nameVi: 'Thánh Hađrianô III', nameLatin: 'Hadrianus III', reign: '884 – 885', birthPlace: 'Roma' },
  { num: 110, nameVi: 'Đức Stêphanô V', nameLatin: 'Stephanus V', reign: '885 – 891', birthPlace: 'Roma' },
  { num: 111, nameVi: 'Đức Phormôsô', nameLatin: 'Formosus', reign: '891 – 896', birthPlace: 'Ostia, Italia' },
  { num: 112, nameVi: 'Đức Bônifaciô VI', nameLatin: 'Bonifacius VI', reign: '896', birthPlace: 'Roma' },
  { num: 113, nameVi: 'Đức Stêphanô VI', nameLatin: 'Stephanus VI', reign: '896 – 897', birthPlace: 'Roma' },
  { num: 114, nameVi: 'Đức Rômanô', nameLatin: 'Romanus', reign: '897', birthPlace: 'Gallese, Italia' },
  { num: 115, nameVi: 'Đức Thêôđôrô II', nameLatin: 'Theodorus II', reign: '897', birthPlace: 'Roma' },
  { num: 116, nameVi: 'Đức Gioan IX', nameLatin: 'Ioannes IX', reign: '898 – 900', birthPlace: 'Tivoli, Italia' },
  { num: 117, nameVi: 'Đức Bênêđictô IV', nameLatin: 'Benedictus IV', reign: '900 – 903', birthPlace: 'Roma' },
  { num: 118, nameVi: 'Đức Lêô V', nameLatin: 'Leo V', reign: '903', birthPlace: 'Ardea, Italia' },
  { num: 119, nameVi: 'Đức Sêrgiô III', nameLatin: 'Sergius III', reign: '904 – 911', birthPlace: 'Roma' },
  { num: 120, nameVi: 'Đức Anastasiô III', nameLatin: 'Anastasius III', reign: '911 – 913', birthPlace: 'Roma' },
  { num: 121, nameVi: 'Đức Lanđô', nameLatin: 'Lando', reign: '913 – 914', birthPlace: 'Sabina, Italia' },
  { num: 122, nameVi: 'Đức Gioan X', nameLatin: 'Ioannes X', reign: '914 – 928', birthPlace: 'Tossignano, Imola' },
  { num: 123, nameVi: 'Đức Lêô VI', nameLatin: 'Leo VI', reign: '928', birthPlace: 'Roma' },
  { num: 124, nameVi: 'Đức Stêphanô VII', nameLatin: 'Stephanus VII', reign: '928 – 931', birthPlace: 'Roma' },
  { num: 125, nameVi: 'Đức Gioan XI', nameLatin: 'Ioannes XI', reign: '931 – 935', birthPlace: 'Roma' },
  { num: 126, nameVi: 'Đức Lêô VII', nameLatin: 'Leo VII', reign: '936 – 939', birthPlace: 'Roma' },
  { num: 127, nameVi: 'Đức Stêphanô VIII', nameLatin: 'Stephanus VIII', reign: '939 – 942', birthPlace: 'Roma' },
  { num: 128, nameVi: 'Đức Marinô II', nameLatin: 'Marinus II', reign: '942 – 946', birthPlace: 'Roma' },
  { num: 129, nameVi: 'Đức Agapêtô II', nameLatin: 'Agapetus II', reign: '946 – 955', birthPlace: 'Roma' },
  { num: 130, nameVi: 'Đức Gioan XII', nameLatin: 'Ioannes XII', reign: '955 – 964', birthPlace: 'Roma' },
  { num: 131, nameVi: 'Đức Bênêđictô V', nameLatin: 'Benedictus V', reign: '964', birthPlace: 'Roma' },
  { num: 132, nameVi: 'Đức Lêô VIII', nameLatin: 'Leo VIII', reign: '963 – 965', birthPlace: 'Roma' },
  { num: 133, nameVi: 'Đức Gioan XIII', nameLatin: 'Ioannes XIII', reign: '965 – 972', birthPlace: 'Roma' },
  { num: 134, nameVi: 'Đức Bênêđictô VI', nameLatin: 'Benedictus VI', reign: '973 – 974', birthPlace: 'Roma' },
  { num: 135, nameVi: 'Đức Bênêđictô VII', nameLatin: 'Benedictus VII', reign: '974 – 983', birthPlace: 'Roma' },
  { num: 136, nameVi: 'Đức Gioan XIV', nameLatin: 'Ioannes XIV', reign: '983 – 984', birthPlace: 'Pavia, Italia' },
  { num: 137, nameVi: 'Đức Gioan XV', nameLatin: 'Ioannes XV', reign: '985 – 996', birthPlace: 'Roma' },
  { num: 138, nameVi: 'Đức Grêgôriô V', nameLatin: 'Gregorius V', reign: '996 – 999', birthPlace: 'Đức' },
  { num: 139, nameVi: 'Đức Silvêstrô II', nameLatin: 'Silvester II', reign: '999 – 1003', birthPlace: 'Auvergne, Pháp', notes: 'Nhà toán học và thiên văn học xuất chúng.' },
  { num: 140, nameVi: 'Đức Gioan XVII', nameLatin: 'Ioannes XVII', reign: '1003', birthPlace: 'Roma' },
  { num: 141, nameVi: 'Đức Gioan XVIII', nameLatin: 'Ioannes XVIII', reign: '1004 – 1009', birthPlace: 'Rapagnano, Italia' },
  { num: 142, nameVi: 'Đức Sêrgiô IV', nameLatin: 'Sergius IV', reign: '1009 – 1012', birthPlace: 'Roma' },
  { num: 143, nameVi: 'Đức Bênêđictô VIII', nameLatin: 'Benedictus VIII', reign: '1012 – 1024', birthPlace: 'Roma' },
  { num: 144, nameVi: 'Đức Gioan XIX', nameLatin: 'Ioannes XIX', reign: '1024 – 1032', birthPlace: 'Roma' },
  { num: 145, nameVi: 'Đức Bênêđictô IX', nameLatin: 'Benedictus IX', reign: '1032 – 1044', birthPlace: 'Roma' },
  { num: 146, nameVi: 'Đức Silvêstrô III', nameLatin: 'Silvester III', reign: '1045', birthPlace: 'Roma' },
  { num: 147, nameVi: 'Đức Bênêđictô IX (Lần 2)', nameLatin: 'Benedictus IX', reign: '1045', birthPlace: 'Roma' },
  { num: 148, nameVi: 'Đức Grêgôriô VI', nameLatin: 'Gregorius VI', reign: '1045 – 1046', birthPlace: 'Roma' },
  { num: 149, nameVi: 'Đức Clêmentê II', nameLatin: 'Clemens II', reign: '1046 – 1047', birthPlace: 'Hornburg, Đức' },
  { num: 150, nameVi: 'Đức Bênêđictô IX (Lần 3)', nameLatin: 'Benedictus IX', reign: '1047 – 1048', birthPlace: 'Roma' },
  { num: 151, nameVi: 'Đức Đamasô II', nameLatin: 'Damasus II', reign: '1048', birthPlace: 'Pildenau, Bavaria' },
  { num: 152, nameVi: 'Thánh Lêô IX', nameLatin: 'Leo IX', reign: '1049 – 1054', birthPlace: 'Eguisheim, Alsace' },
  { num: 153, nameVi: 'Đức Victor II', nameLatin: 'Victor II', reign: '1055 – 1057', birthPlace: 'Dollnstein, Đức' },
  { num: 154, nameVi: 'Đức Stêphanô IX', nameLatin: 'Stephanus IX', reign: '1057 – 1058', birthPlace: 'Lorraine, Pháp' },
  { num: 155, nameVi: 'Đức Nicôla II', nameLatin: 'Nicolaus II', reign: '1058 – 1061', birthPlace: 'Chevron, Savoy' },
  { num: 156, nameVi: 'Đức Alêxandê II', nameLatin: 'Alexander II', reign: '1061 – 1073', birthPlace: 'Milan, Italia' },
  { num: 157, nameVi: 'Thánh Grêgôriô VII', nameLatin: 'Gregorius VII', reign: '1073 – 1085', birthPlace: 'Sovana, Tuscany', notes: 'Khởi xướng cuộc Cải cách Grêgôriô bảo vệ quyền tự do của Giáo hội.' },
  { num: 158, nameVi: 'Chân phước Victor III', nameLatin: 'Victor III', reign: '1086 – 1087', birthPlace: 'Benevento, Italia' },
  { num: 159, nameVi: 'Chân phước Urbanô II', nameLatin: 'Urbanus II', reign: '1088 – 1099', birthPlace: 'Châtillon-sur-Marne, Pháp' },
  { num: 160, nameVi: 'Đức Paschal II', nameLatin: 'Paschalis II', reign: '1099 – 1118', birthPlace: 'Bleda, Romagna' },
  { num: 161, nameVi: 'Đức Gêlasiô II', nameLatin: 'Gelasius II', reign: '1118 – 1119', birthPlace: 'Gaeta, Italia' },
  { num: 162, nameVi: 'Đức Callistô II', nameLatin: 'Callistus II', reign: '1119 – 1124', birthPlace: 'Quingey, Pháp' },
  { num: 163, nameVi: 'Đức Hônôriô II', nameLatin: 'Honorius II', reign: '1124 – 1130', birthPlace: 'Casalfiumanese, Imola' },
  { num: 164, nameVi: 'Đức Innocentê II', nameLatin: 'Innocentius II', reign: '1130 – 1143', birthPlace: 'Roma' },
  { num: 165, nameVi: 'Đức Cêlestinô II', nameLatin: 'Caelestinus II', reign: '1143 – 1144', birthPlace: 'Città di Castello, Italia' },
  { num: 166, nameVi: 'Đức Luciô II', nameLatin: 'Lucius II', reign: '1144 – 1145', birthPlace: 'Bologna, Italia' },
  { num: 167, nameVi: 'Chân phước Eugêniô III', nameLatin: 'Eugenius III', reign: '1145 – 1153', birthPlace: 'Pisa, Italia' },
  { num: 168, nameVi: 'Đức Anastasiô IV', nameLatin: 'Anastasius IV', reign: '1153 – 1154', birthPlace: 'Roma' },
  { num: 169, nameVi: 'Đức Hađrianô IV', nameLatin: 'Hadrianus IV', reign: '1154 – 1159', birthPlace: 'Abbots Langley, Anh', notes: 'Vị Giáo hoàng duy nhất là người Anh trong lịch sử.' },
  { num: 170, nameVi: 'Đức Alêxandê III', nameLatin: 'Alexander III', reign: '1159 – 1181', birthPlace: 'Siena, Italia', notes: 'Đặt viên đá đầu tiên xây dựng Nhà thờ Đức Bà Paris (1163).' },
  { num: 171, nameVi: 'Đức Luciô III', nameLatin: 'Lucius III', reign: '1181 – 1185', birthPlace: 'Lucca, Italia' },
  { num: 172, nameVi: 'Đức Urbanô III', nameLatin: 'Urbanus III', reign: '1185 – 1187', birthPlace: 'Cuggiono, Milan' },
  { num: 173, nameVi: 'Đức Grêgôriô VIII', nameLatin: 'Gregorius VIII', reign: '1187', birthPlace: 'Benevento, Italia' },
  { num: 174, nameVi: 'Đức Clêmentê III', nameLatin: 'Clemens III', reign: '1187 – 1191', birthPlace: 'Roma' },
  { num: 175, nameVi: 'Đức Cêlestinô III', nameLatin: 'Caelestinus III', reign: '1191 – 1198', birthPlace: 'Roma' },
  { num: 176, nameVi: 'Đức Innocentê III', nameLatin: 'Innocentius III', reign: '1198 – 1216', birthPlace: 'Gavignano, Italia', notes: 'Tổ chức Công đồng Lateranô IV (1215), hỗ trợ Thánh Phanxicô và Đaminh.' },
  { num: 177, nameVi: 'Đức Hônôriô III', nameLatin: 'Honorius III', reign: '1216 – 1227', birthPlace: 'Roma' },
  { num: 178, nameVi: 'Đức Grêgôriô IX', nameLatin: 'Gregorius IX', reign: '1227 – 1241', birthPlace: 'Anagni, Italia' },
  { num: 179, nameVi: 'Đức Cêlestinô IV', nameLatin: 'Caelestinus IV', reign: '1241', birthPlace: 'Milan, Italia' },
  { num: 180, nameVi: 'Đức Innocentê IV', nameLatin: 'Innocentius IV', reign: '1243 – 1254', birthPlace: 'Genoa, Italia' },
  { num: 181, nameVi: 'Đức Alêxandê IV', nameLatin: 'Alexander IV', reign: '1254 – 1261', birthPlace: 'Anagni, Italia' },
  { num: 182, nameVi: 'Đức Urbanô IV', nameLatin: 'Urbanus IV', reign: '1261 – 1264', birthPlace: 'Troyes, Pháp' },
  { num: 183, nameVi: 'Đức Clêmentê IV', nameLatin: 'Clemens IV', reign: '1265 – 1268', birthPlace: 'Saint-Gilles, Pháp' },
  { num: 184, nameVi: 'Chân phước Grêgôriô X', nameLatin: 'Gregorius X', reign: '1271 – 1276', birthPlace: 'Piacenza, Italia' },
  { num: 185, nameVi: 'Chân phước Innocentê V', nameLatin: 'Innocentius V', reign: '1276', birthPlace: 'Champagny, Savoy' },
  { num: 186, nameVi: 'Đức Hađrianô V', nameLatin: 'Hadrianus V', reign: '1276', birthPlace: 'Genoa, Italia' },
  { num: 187, nameVi: 'Đức Gioan XXI', nameLatin: 'Ioannes XXI', reign: '1276 – 1277', birthPlace: 'Lisbon, Bồ Đào Nha' },
  { num: 188, nameVi: 'Đức Nicôla III', nameLatin: 'Nicolaus III', reign: '1277 – 1280', birthPlace: 'Roma' },
  { num: 189, nameVi: 'Đức Martinô IV', nameLatin: 'Martinus IV', reign: '1281 – 1285', birthPlace: 'Meuvrain, Pháp' },
  { num: 190, nameVi: 'Đức Hônôriô IV', nameLatin: 'Honorius IV', reign: '1285 – 1287', birthPlace: 'Roma' },
  { num: 191, nameVi: 'Đức Nicôla IV', nameLatin: 'Nicolaus IV', reign: '1288 – 1292', birthPlace: 'Lisciano, Ascoli' },
  { num: 192, nameVi: 'Thánh Cêlestinô V', nameLatin: 'Caelestinus V', reign: '1294', birthPlace: 'Sant\'Angelo Limosano, Italia', notes: 'Tu sĩ ẩn tu, từ nhiệm vì khiêm nhường.' },
  { num: 193, nameVi: 'Đức Bônifaciô VIII', nameLatin: 'Bonifacius VIII', reign: '1294 – 1303', birthPlace: 'Anagni, Italia', notes: 'Khai mở Năm Thánh đầu tiên trong lịch sử (1300).' },
  { num: 194, nameVi: 'Chân phước Bênêđictô XI', nameLatin: 'Benedictus XI', reign: '1303 – 1304', birthPlace: 'Treviso, Italia' },
  { num: 195, nameVi: 'Đức Clêmentê V', nameLatin: 'Clemens V', reign: '1305 – 1314', birthPlace: 'Villandraut, Pháp', notes: 'Khởi đầu thời kỳ Giáo hoàng ở Avignon.' },
  { num: 196, nameVi: 'Đức Gioan XXII', nameLatin: 'Ioannes XXII', reign: '1316 – 1334', birthPlace: 'Cahors, Pháp' },
  { num: 197, nameVi: 'Đức Bênêđictô XII', nameLatin: 'Benedictus XII', reign: '1334 – 1342', birthPlace: 'Saverdun, Pháp' },
  { num: 198, nameVi: 'Đức Clêmentê VI', nameLatin: 'Clemens VI', reign: '1342 – 1352', birthPlace: 'Rosiers-d\'Égletons, Pháp' },
  { num: 199, nameVi: 'Đức Innocentê VI', nameLatin: 'Innocentius VI', reign: '1352 – 1362', birthPlace: 'Les Monts, Pháp' },
  { num: 200, nameVi: 'Chân phước Urbanô V', nameLatin: 'Urbanus V', reign: '1362 – 1370', birthPlace: 'Grizac, Pháp' },
  { num: 201, nameVi: 'Đức Grêgôriô XI', nameLatin: 'Gregorius XI', reign: '1370 – 1378', birthPlace: 'Rosiers-d\'Égletons, Pháp', notes: 'Đưa Tòa Thánh từ Avignon trở về Roma theo lời khuyên của Thánh Catarina thành Siena.' },
  { num: 202, nameVi: 'Đức Urbanô VI', nameLatin: 'Urbanus VI', reign: '1378 – 1389', birthPlace: 'Napoli, Italia' },
  { num: 203, nameVi: 'Đức Bônifaciô IX', nameLatin: 'Bonifacius IX', reign: '1389 – 1404', birthPlace: 'Napoli, Italia' },
  { num: 204, nameVi: 'Đức Innocentê VII', nameLatin: 'Innocentius VII', reign: '1404 – 1406', birthPlace: 'Sulmona, Italia' },
  { num: 205, nameVi: 'Đức Grêgôriô XII', nameLatin: 'Gregorius XII', reign: '1406 – 1415', birthPlace: 'Venice, Italia', notes: 'Từ nhiệm tại Công đồng Constance để chấm dứt cuộc Ly giáo Tây phương.' },
  { num: 206, nameVi: 'Đức Martinô V', nameLatin: 'Martinus V', reign: '1417 – 1431', birthPlace: 'Genazzano, Italia' },
  { num: 207, nameVi: 'Đức Eugêniô IV', nameLatin: 'Eugenius IV', reign: '1431 – 1447', birthPlace: 'Venice, Italia' },
  { num: 208, nameVi: 'Đức Nicôla V', nameLatin: 'Nicolaus V', reign: '1447 – 1455', birthPlace: 'Sarzana, Liguria', notes: 'Sáng lập Thư viện Vatican.' },
  { num: 209, nameVi: 'Đức Callistô III', nameLatin: 'Callistus III', reign: '1455 – 1458', birthPlace: 'Xàtiva, Valencia, Tây Ban Nha' },
  { num: 210, nameVi: 'Đức Piô II', nameLatin: 'Pius II', reign: '1458 – 1464', birthPlace: 'Corsignano, Siena' },
  { num: 211, nameVi: 'Đức Phaolô II', nameLatin: 'Paulus II', reign: '1464 – 1471', birthPlace: 'Venice, Italia' },
  { num: 212, nameVi: 'Đức Xíttô IV', nameLatin: 'Sixtus IV', reign: '1471 – 1484', birthPlace: 'Celle Ligure, Italia', notes: 'Xây dựng Nhà nguyện Sistine nổi tiếng thế giới.' },
  { num: 213, nameVi: 'Đức Innocentê VIII', nameLatin: 'Innocentius VIII', reign: '1484 – 1492', birthPlace: 'Genoa, Italia' },
  { num: 214, nameVi: 'Đức Alêxandê VI', nameLatin: 'Alexander VI', reign: '1492 – 1503', birthPlace: 'Xàtiva, Valencia, Tây Ban Nha' },
  { num: 215, nameVi: 'Đức Piô III', nameLatin: 'Pius III', reign: '1503', birthPlace: 'Siena, Italia' },
  { num: 216, nameVi: 'Đức Giuliô II', nameLatin: 'Iulius II', reign: '1503 – 1513', birthPlace: 'Albisola, Savona', notes: 'Khởi công xây dựng Vương cung thánh đường Thánh Phêrô mới, bảo trợ Michelangelo & Raphael.' },
  { num: 217, nameVi: 'Đức Lêô X', nameLatin: 'Leo X', reign: '1513 – 1521', birthPlace: 'Florence, Italia (Dòng họ Medici)' },
  { num: 218, nameVi: 'Đức Hađrianô VI', nameLatin: 'Hadrianus VI', reign: '1522 – 1523', birthPlace: 'Utrecht, Hà Lan', notes: 'Vị Giáo hoàng duy nhất là người Hà Lan.' },
  { num: 219, nameVi: 'Đức Clêmentê VII', nameLatin: 'Clemens VII', reign: '1523 – 1534', birthPlace: 'Florence, Italia (Dòng họ Medici)' },
  { num: 220, nameVi: 'Đức Phaolô III', nameLatin: 'Paulus III', reign: '1534 – 1549', birthPlace: 'Canino, Lazio', notes: 'Triệu tập Công đồng Trentô (1545), phê chuẩn Dòng Tên.' },
  { num: 221, nameVi: 'Đức Giuliô III', nameLatin: 'Iulius III', reign: '1550 – 1555', birthPlace: 'Roma' },
  { num: 222, nameVi: 'Đức Marcellô II', nameLatin: 'Marcellus II', reign: '1555', birthPlace: 'Montefano, Macerata' },
  { num: 223, nameVi: 'Đức Phaolô IV', nameLatin: 'Paulus IV', reign: '1555 – 1559', birthPlace: 'Capriglia Irpina, Campania' },
  { num: 224, nameVi: 'Đức Piô IV', nameLatin: 'Pius IV', reign: '1559 – 1565', birthPlace: 'Milan, Italia', notes: 'Bế mạc Công đồng Trentô (1563).' },
  { num: 225, nameVi: 'Thánh Piô V', nameLatin: 'Pius V', reign: '1566 – 1572', birthPlace: 'Bosco Marengo, Italia', notes: 'Ban hành Thánh Lễ Tridentinô và Kinh Mân Côi chiến thắng Lepanto (1571).' },
  { num: 226, nameVi: 'Đức Grêgôriô XIII', nameLatin: 'Gregorius XIII', reign: '1572 – 1585', birthPlace: 'Bologna, Italia', notes: 'Ban hành Lịch Gregory chuẩn quốc tế (Dương lịch năm 1582).' },
  { num: 227, nameVi: 'Đức Xíttô V', nameLatin: 'Sixtus V', reign: '1585 – 1590', birthPlace: 'Grottammare, Marche' },
  { num: 228, nameVi: 'Đức Urbanô VII', nameLatin: 'Urbanus VII', reign: '1590', birthPlace: 'Roma', notes: 'Triều đại ngắn nhất lịch sử (12 ngày).' },
  { num: 229, nameVi: 'Đức Grêgôriô XIV', nameLatin: 'Gregorius XIV', reign: '1590 – 1591', birthPlace: 'Somma Lombardo, Varese' },
  { num: 230, nameVi: 'Đức Innocentê IX', nameLatin: 'Innocentius IX', reign: '1591', birthPlace: 'Bologna, Italia' },
  { num: 231, nameVi: 'Đức Clêmentê VIII', nameLatin: 'Clemens VIII', reign: '1592 – 1605', birthPlace: 'Fano, Marche' },
  { num: 232, nameVi: 'Đức Lêô XI', nameLatin: 'Leo XI', reign: '1605', birthPlace: 'Florence, Italia' },
  { num: 233, nameVi: 'Đức Phaolô V', nameLatin: 'Paulus V', reign: '1605 – 1621', birthPlace: 'Roma', notes: 'Hoàn thành mặt tiền Vương cung thánh đường Thánh Phêrô.' },
  { num: 234, nameVi: 'Đức Grêgôriô XV', nameLatin: 'Gregorius XV', reign: '1621 – 1623', birthPlace: 'Bologna, Italia', notes: 'Thành lập Bộ Truyền giáo (Propaganda Fide, 1622).' },
  { num: 235, nameVi: 'Đức Urbanô VIII', nameLatin: 'Urbanus VIII', reign: '1623 – 1644', birthPlace: 'Florence, Italia', notes: 'Cung hiến Vương cung thánh đường Thánh Phêrô (1626).' },
  { num: 236, nameVi: 'Đức Innocentê X', nameLatin: 'Innocentius X', reign: '1644 – 1655', birthPlace: 'Roma' },
  { num: 237, nameVi: 'Đức Alêxandê VII', nameLatin: 'Alexander VII', reign: '1655 – 1667', birthPlace: 'Siena, Italia', notes: 'Ủy thác Bernini thiết kế Quảng trường Thánh Phêrô với hàng cột Colonnade hùng vĩ.' },
  { num: 238, nameVi: 'Đức Clêmentê IX', nameLatin: 'Clemens IX', reign: '1667 – 1669', birthPlace: 'Pistoia, Tuscany' },
  { num: 239, nameVi: 'Đức Clêmentê X', nameLatin: 'Clemens X', reign: '1670 – 1676', birthPlace: 'Roma' },
  { num: 240, nameVi: 'Chân phước Innocentê XI', nameLatin: 'Innocentius XI', reign: '1676 – 1689', birthPlace: 'Como, Lombardy' },
  { num: 241, nameVi: 'Đức Alêxandê VIII', nameLatin: 'Alexander VIII', reign: '1689 – 1691', birthPlace: 'Venice, Italia' },
  { num: 242, nameVi: 'Đức Innocentê XII', nameLatin: 'Innocentius XII', reign: '1691 – 1700', birthPlace: 'Spinazzola, Puglia' },
  { num: 243, nameVi: 'Đức Clêmentê XI', nameLatin: 'Clemens XI', reign: '1700 – 1721', birthPlace: 'Urbino, Marche' },
  { num: 244, nameVi: 'Đức Innocentê XIII', nameLatin: 'Innocentius XIII', reign: '1721 – 1724', birthPlace: 'Poli, Lazio' },
  { num: 245, nameVi: 'Đức Bênêđictô XIII', nameLatin: 'Benedictus XIII', reign: '1724 – 1730', birthPlace: 'Gravina in Puglia, Bari' },
  { num: 246, nameVi: 'Đức Clêmentê XII', nameLatin: 'Clemens XII', reign: '1730 – 1740', birthPlace: 'Florence, Italia' },
  { num: 247, nameVi: 'Đức Bênêđictô XIV', nameLatin: 'Benedictus XIV', reign: '1740 – 1758', birthPlace: 'Bologna, Italia' },
  { num: 248, nameVi: 'Đức Clêmentê XIII', nameLatin: 'Clemens XIII', reign: '1758 – 1769', birthPlace: 'Venice, Italia' },
  { num: 249, nameVi: 'Đức Clêmentê XIV', nameLatin: 'Clemens XIV', reign: '1769 – 1774', birthPlace: 'Sant\'Arcangelo di Romagna' },
  { num: 250, nameVi: 'Đức Piô VI', nameLatin: 'Pius VI', reign: '1775 – 1799', birthPlace: 'Cesena, Romagna' },
  { num: 251, nameVi: 'Đức Piô VII', nameLatin: 'Pius VII', reign: '1800 – 1823', birthPlace: 'Cesena, Romagna' },
  { num: 252, nameVi: 'Đức Lêô XII', nameLatin: 'Leo XII', reign: '1823 – 1829', birthPlace: 'Genga, Marche' },
  { num: 253, nameVi: 'Đức Piô VIII', nameLatin: 'Pius VIII', reign: '1829 – 1830', birthPlace: 'Cingoli, Marche' },
  { num: 254, nameVi: 'Đức Grêgôriô XVI', nameLatin: 'Gregorius XVI', reign: '1831 – 1846', birthPlace: 'Belluno, Veneto' },
  { num: 255, nameVi: 'Chân phước Piô IX', nameLatin: 'Pius IX', reign: '1846 – 1878', birthPlace: 'Senigallia, Marche', notes: 'Triều đại dài nhất lịch sử (31 năm 7 tháng), tuyên tín Tín điều Đức Mẹ Vô Nhiễm Nguyên Tội (1854) & Công đồng Vatican I.' },
  { num: 256, nameVi: 'Đức Lêô XIII', nameLatin: 'Leo XIII', reign: '1878 – 1903', birthPlace: 'Carpineto Romano, Lazio', notes: 'Tác giả Thông điệp Rerum Novarum (1891) đặt nền móng Học thuyết Xã hội Công giáo.' },
  { num: 257, nameVi: 'Thánh Piô X', nameLatin: 'Pius X', reign: '1903 – 1914', birthPlace: 'Riese, Treviso', notes: 'Khuyến khích rước lễ sớm và thường xuyên, cải tổ Giáo luật.' },
  { num: 258, nameVi: 'Đức Bênêđictô XV', nameLatin: 'Benedictus XV', reign: '1914 – 1922', birthPlace: 'Genoa, Italia', notes: 'Giáo hoàng của Hòa bình trong Thế chiến I, ban hành Bộ Giáo luật 1917.' },
  { num: 259, nameVi: 'Đức Piô XI', nameLatin: 'Pius XI', reign: '1922 – 1939', birthPlace: 'Desio, Milan', notes: 'Ký Hiệp ước Lateranô (1929) khai sinh Thành quốc Vatican độc lập.' },
  { num: 260, nameVi: 'Đáng kính Piô XII', nameLatin: 'Pius XII', reign: '1939 – 1958', birthPlace: 'Roma', notes: 'Tuyên tín Tín điều Đức Mẹ Hồn Xác Lên Trời (1950), dẫn dắt Giáo hội qua Thế chiến II.' },
  { num: 261, nameVi: 'Thánh Gioan XXIII', nameLatin: 'Ioannes XXIII', reign: '1958 – 1963', birthPlace: 'Sotto il Monte, Bergamo', notes: 'Triệu tập Công đồng Vatican II lịch sử, ban hành Sắc chỉ thành lập Giáo phận Mỹ Tho (1960).' },
  { num: 262, nameVi: 'Thánh Phaolô VI', nameLatin: 'Paulus VI', reign: '1963 – 1978', birthPlace: 'Concesio, Brescia', notes: 'Hoàn tất và thực thi Công đồng Vatican II, vị Giáo hoàng đầu tiên đi công du quốc tế khắp các châu lục.' },
  { num: 263, nameVi: 'Chân phước Gioan Phaolô I', nameLatin: 'Ioannes Paulus I', reign: '1978 (33 ngày)', birthPlace: 'Canale d\'Agordo, Belluno', notes: 'Vị Giáo hoàng của nụ cười, triều đại kéo dài 33 ngày.' },
  { num: 264, nameVi: 'Thánh Gioan Phaolô II', nameLatin: 'Ioannes Paulus II', reign: '1978 – 2005 (26 năm)', birthPlace: 'Wadowice, Ba Lan', notes: 'Karol Józef Wojtyła — Vị Giáo hoàng vĩ đại của thời đại, công du 129 quốc gia, người sáng lập Ngày Giới Trẻ Thế Giới (WYD).' },
  { num: 265, nameVi: 'Đức Bênêđictô XVI', nameLatin: 'Benedictus XVI', reign: '2005 – 2013 (8 năm)', birthPlace: 'Marktl am Inn, Bavaria, Đức', notes: 'Joseph Ratzinger — Nhà thần học kiệt xuất hàng đầu thế kỷ XX, bảo vệ chân lý và vẻ đẹp phụng vụ thánh.' },
  { num: 266, nameVi: 'Đức Phanxicô', nameLatin: 'Franciscus', reign: '2013 – 2024', birthPlace: 'Buenos Aires, Argentina', notes: 'Jorge Mario Bergoglio, S.J. — Vị Giáo hoàng đầu tiên thuộc Dòng Tên và đến từ châu Mỹ Latinh, thúc đẩy lòng thương xót và tình huynh đệ nhân loại.' },
  { num: 267, nameVi: 'Đức Lêô XIV', nameLatin: 'Leo XIV', reign: '2024 – nay', birthPlace: 'Roma, Italia', notes: 'Đức Thánh Cha đương kim thứ 267 của Giáo hội Công giáo Hoàn Vũ. Ngài chọn tông hiệu Lêô XIV tiếp nối truyền thống canh tân giáo lý, bảo vệ sự hiệp nhất và tình huynh đệ nhân loại.', imageUrl: '/images/pope_leo_xiv.jpg' }
];
