import { BibleBookInfo } from './types';

/**
 * Danh mục 73 Cuốn Sách Kinh Thánh Công Giáo Trọn Bộ (46 Cựu Ước + 27 Tân Ước)
 * Cào dữ liệu trực tuyến & nhúng trực tiếp từ https://augustino.net/kinh-thanh
 */
export const BIBLE_BOOKS: BibleBookInfo[] = [
  // =========================================================================
  // I. CỰU ƯỚC (46 SÁCH)
  // =========================================================================

  // 1. Ngũ Thư (5 Sách)
  {
    id: 'sang-the',
    augustinoSlug: 'sach-sang-the',
    code: 'St',
    name: 'Sách Sáng Thế',
    shortName: 'Sáng Thế',
    testament: 'old',
    group: 'pentateuch',
    groupLabel: 'Ngũ Thư',
    totalChapters: 50,
    summary: 'Khởi nguyên vũ trụ, công trình tạo dựng, Vườn Địa Đàng, giao ước với Áp-ra-ham, I-sa-ác, Gia-cóp và Giu-se tại Ai Cập.',
    onlineUrl: 'https://augustino.net/sach-sang-the',
    iframeUrl: 'https://augustino.net/sach-sang-the'
  },
  {
    id: 'xuat-hanh',
    augustinoSlug: 'sach-xuat-hanh',
    code: 'Xh',
    name: 'Sách Xuất Hành',
    shortName: 'Xuất Hành',
    testament: 'old',
    group: 'pentateuch',
    groupLabel: 'Ngũ Thư',
    totalChapters: 40,
    summary: 'Thiên Chúa giải phóng dân Israel khỏi ách nô lệ Ai Cập, vượt Biển Đỏ và ban Thập Giới trên núi Sinai.',
    onlineUrl: 'https://augustino.net/sach-xuat-hanh',
    iframeUrl: 'https://augustino.net/sach-xuat-hanh'
  },
  {
    id: 'le-vi',
    augustinoSlug: 'sach-le-vi',
    code: 'Lv',
    name: 'Sách Lê-vi',
    shortName: 'Lê-vi',
    testament: 'old',
    group: 'pentateuch',
    groupLabel: 'Ngũ Thư',
    totalChapters: 27,
    summary: 'Luật tế tự, phụng vụ thánh điện, chức tư tế và luật thanh sạch dành cho Dân Thánh của Chúa.',
    onlineUrl: 'https://augustino.net/sach-le-vi',
    iframeUrl: 'https://augustino.net/sach-le-vi'
  },
  {
    id: 'dan-so',
    augustinoSlug: 'sach-dan-so',
    code: 'Ds',
    name: 'Sách Dân Số',
    shortName: 'Dân Số',
    testament: 'old',
    group: 'pentateuch',
    groupLabel: 'Ngũ Thư',
    totalChapters: 36,
    summary: 'Kiểm tra dân số và hành trình 40 năm trong sa mạc tiến về Đất Hứa dưới sự dẫn dắt của Thiên Chúa.',
    onlineUrl: 'https://augustino.net/sach-dan-so',
    iframeUrl: 'https://augustino.net/sach-dan-so'
  },
  {
    id: 'de-nhi-luat',
    augustinoSlug: 'sach-de-nhi-luat',
    code: 'Dnl',
    name: 'Sách Đệ Nhị Luật',
    shortName: 'Đệ Nhị Luật',
    testament: 'old',
    group: 'pentateuch',
    groupLabel: 'Ngũ Thư',
    totalChapters: 34,
    summary: 'Lời trăn trối của Môsê, nhắc lại Giao Ước và luật mến Chúa hết lòng, hết linh hồn, hết trí khôn.',
    onlineUrl: 'https://augustino.net/sach-de-nhi-luat',
    iframeUrl: 'https://augustino.net/sach-de-nhi-luat'
  },

  // 2. Lịch Sử Cựu Ước (16 Sách)
  {
    id: 'gio-su-e',
    augustinoSlug: 'sach-gio-sue',
    code: 'Gs',
    name: 'Sách Giô-suê',
    shortName: 'Giô-suê',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 24,
    summary: 'Giô-suê dẫn dân Israel vượt sông Gio-đan, hạ thành Giê-ri-khô và chia đất Canaan cho 12 chi tộc.',
    onlineUrl: 'https://augustino.net/sach-gio-sue',
    iframeUrl: 'https://augustino.net/sach-gio-sue'
  },
  {
    id: 'thu-lanh',
    augustinoSlug: 'sach-thu-lanh',
    code: 'Tl',
    name: 'Sách Thủ Lãnh',
    shortName: 'Thủ Lãnh',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 21,
    summary: 'Thời kỳ các Thủ lãnh (Gideon, Sam-sôn, Đê-vô-ra) bảo vệ dân và kêu gọi lòng trung thành với Chúa.',
    onlineUrl: 'https://augustino.net/sach-thu-lanh',
    iframeUrl: 'https://augustino.net/sach-thu-lanh'
  },
  {
    id: 'rut',
    augustinoSlug: 'sach-rut',
    code: 'R',
    name: 'Sách Rút',
    shortName: 'Rút',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 4,
    summary: 'Câu chuyện cảm động về lòng hiếu thảo của bà Rút dân ngoại, tổ mẫu của Vua Đavít và Chúa Giêsu.',
    onlineUrl: 'https://augustino.net/sach-rut',
    iframeUrl: 'https://augustino.net/sach-rut'
  },
  {
    id: 'sa-mu-en-1',
    augustinoSlug: 'sach-sa-mu-en-1',
    code: '1Sm',
    name: 'Sách Sa-mu-en 1',
    shortName: '1 Sa-mu-en',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 31,
    summary: 'Ngôn sứ Sa-mu-en, Vua Sa-un và tuổi trẻ của Vua Đavít đánh bại tên khổng lồ Gô-li-át.',
    onlineUrl: 'https://augustino.net/sach-sa-mu-en-1',
    iframeUrl: 'https://augustino.net/sach-sa-mu-en-1'
  },
  {
    id: 'sa-mu-en-2',
    augustinoSlug: 'sach-sa-mu-en-2',
    code: '2Sm',
    name: 'Sách Sa-mu-en 2',
    shortName: '2 Sa-mu-en',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 24,
    summary: 'Triều đại vinh quang của Vua Đavít, thống nhất đất nước và đưa Hòm Bia Thiên Chúa về Giê-ru-sa-lem.',
    onlineUrl: 'https://augustino.net/sach-sa-mu-en-2',
    iframeUrl: 'https://augustino.net/sach-sa-mu-en-2'
  },
  {
    id: 'cac-vua-1',
    augustinoSlug: 'sach-cac-vua-1',
    code: '1V',
    name: 'Sách Các Vua 1',
    shortName: '1 Các Vua',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 22,
    summary: 'Sự khôn ngoan của Vua Sa-lô-môn, việc xây Đền Thờ và sứ vụ ngôn sứ Ê-li-a trên núi Cát-minh.',
    onlineUrl: 'https://augustino.net/sach-cac-vua-1',
    iframeUrl: 'https://augustino.net/sach-cac-vua-1'
  },
  {
    id: 'cac-vua-2',
    augustinoSlug: 'sach-cac-vua-2',
    code: '2V',
    name: 'Sách Các Vua 2',
    shortName: '2 Các Vua',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 25,
    summary: 'Ngôn sứ Ê-li-sê, sự sụp đổ của vương quốc phía Bắc và biến cố lưu đày Ba-by-lon của Giu-đa.',
    onlineUrl: 'https://augustino.net/sach-cac-vua-2',
    iframeUrl: 'https://augustino.net/sach-cac-vua-2'
  },
  {
    id: 'su-bien-1',
    augustinoSlug: 'sach-su-bien-1',
    code: '1Sb',
    name: 'Sách Sử Biên 1',
    shortName: '1 Sử Biên',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 29,
    summary: 'Gia phả từ A-đam đến Đavít và việc chuẩn bị vật liệu xây cất Đền Thờ Thiên Chúa.',
    onlineUrl: 'https://augustino.net/sach-su-bien-1',
    iframeUrl: 'https://augustino.net/sach-su-bien-1'
  },
  {
    id: 'su-bien-2',
    augustinoSlug: 'sach-su-bien-2',
    code: '2Sb',
    name: 'Sách Sử Biên 2',
    shortName: '2 Sử Biên',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 36,
    summary: 'Lịch sử phụng vụ Đền Thờ qua các triều vua Giu-đa cho đến chiếu chỉ hồi hương của Vua Ky-rô.',
    onlineUrl: 'https://augustino.net/sach-su-bien-2',
    iframeUrl: 'https://augustino.net/sach-su-bien-2'
  },
  {
    id: 'et-ra',
    augustinoSlug: 'sach-et-ra',
    code: 'Er',
    name: 'Sách Ét-ra',
    shortName: 'Ét-ra',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 10,
    summary: 'Cuộc hồi hương từ Ba-by-lon, tái thiết Đền Thờ Giê-ru-sa-lem và canh tân đời sống Lề Luật.',
    onlineUrl: 'https://augustino.net/sach-et-ra',
    iframeUrl: 'https://augustino.net/sach-et-ra'
  },
  {
    id: 'no-khe-mi-a',
    augustinoSlug: 'sach-no-khe-mi-a',
    code: 'Nkm',
    name: 'Sách Nơ-khe-mi-a',
    shortName: 'Nơ-khe-mi-a',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 13,
    summary: 'Nơ-khe-mi-a lãnh đạo công cuộc xây dựng lại tường thành Giê-ru-sa-lem trong gian truân.',
    onlineUrl: 'https://augustino.net/sach-no-khe-mi-a',
    iframeUrl: 'https://augustino.net/sach-no-khe-mi-a'
  },
  {
    id: 'to-bi-a',
    augustinoSlug: 'sach-to-bi-a',
    code: 'Tb',
    name: 'Sách Tô-bi-a',
    shortName: 'Tô-bi-a',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 14,
    summary: 'Mẫu gương đạo đức gia đình, việc bác ái chôn táng kẻ chết và sự đồng hành của Tổng Lãnh Thiên Thần Ra-pha-en.',
    onlineUrl: 'https://augustino.net/sach-to-bi-a',
    iframeUrl: 'https://augustino.net/sach-to-bi-a'
  },
  {
    id: 'giu-di-tha',
    augustinoSlug: 'sach-giu-di-tha',
    code: 'Gdt',
    name: 'Sách Giu-đi-tha',
    shortName: 'Giu-đi-tha',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 16,
    summary: 'Người phụ nữ quả cảm cứu dân thành Bê-thu-li-a khỏi bàn tay tướng giặc Hô-lô-phéc-nê.',
    onlineUrl: 'https://augustino.net/sach-giu-di-tha',
    iframeUrl: 'https://augustino.net/sach-giu-di-tha'
  },
  {
    id: 'et-te',
    augustinoSlug: 'sach-et-te',
    code: 'Et',
    name: 'Sách Ét-te',
    shortName: 'Ét-te',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 10,
    summary: 'Hoàng hậu Ét-te liều mạng cứu toàn thể đồng bào Do Thái khỏi âm mưu hủy diệt của quan Ha-man.',
    onlineUrl: 'https://augustino.net/sach-et-te',
    iframeUrl: 'https://augustino.net/sach-et-te'
  },
  {
    id: 'ma-ca-be-1',
    augustinoSlug: 'sach-ma-ca-be-1',
    code: '1Mcb',
    name: 'Sách Ma-ca-bê 1',
    shortName: '1 Ma-ca-bê',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 16,
    summary: 'Cuộc khởi nghĩa hào hùng của anh em nhà Ma-ca-bê bảo vệ đức tin và thanh tẩy Đền Thờ.',
    onlineUrl: 'https://augustino.net/sach-ma-ca-be-1',
    iframeUrl: 'https://augustino.net/sach-ma-ca-be-1'
  },
  {
    id: 'ma-ca-be-2',
    augustinoSlug: 'sach-ma-ca-be-2',
    code: '2Mcb',
    name: 'Sách Ma-ca-bê 2',
    shortName: '2 Ma-ca-bê',
    testament: 'old',
    group: 'historical_ot',
    groupLabel: 'Lịch Sử Cựu Ước',
    totalChapters: 15,
    summary: 'Gương tử đạo bất khuất của 7 anh em và người mẹ, niềm tin xác tín vào sự sống lại của thân xác.',
    onlineUrl: 'https://augustino.net/sach-ma-ca-be-2',
    iframeUrl: 'https://augustino.net/sach-ma-ca-be-2'
  },

  // 3. Giáo Huấn & Thi Văn (7 Sách)
  {
    id: 'giop',
    augustinoSlug: 'sach-giop',
    code: 'G',
    name: 'Sách Gióp',
    shortName: 'Gióp',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 42,
    summary: 'Mầu nhiệm đau khổ của người công chính, lòng kiên trung tín thác tuyệt đối vào Thiên Chúa.',
    onlineUrl: 'https://augustino.net/sach-giop',
    iframeUrl: 'https://augustino.net/sach-giop'
  },
  {
    id: 'thanh-vinh',
    augustinoSlug: 'sach-thanh-vinh',
    code: 'Tv',
    name: 'Sách Thánh Vịnh (150 Bài)',
    shortName: 'Thánh Vịnh',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 150,
    summary: 'Lời cầu nguyện, ngợi khen, tạ ơn, sám hối và tin cậy của Dân Chúa xuyên suốt mọi thời đại.',
    onlineUrl: 'https://augustino.net/sach-thanh-vinh',
    iframeUrl: 'https://augustino.net/sach-thanh-vinh'
  },
  {
    id: 'cham-ngon',
    augustinoSlug: 'sach-cham-ngon',
    code: 'Cn',
    name: 'Sách Châm Ngôn',
    shortName: 'Châm Ngôn',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 31,
    summary: 'Những lời răn dạy khôn ngoan về lối sống đạo đức, kính sợ Chúa và cách đối nhân xử thế.',
    onlineUrl: 'https://augustino.net/sach-cham-ngon',
    iframeUrl: 'https://augustino.net/sach-cham-ngon'
  },
  {
    id: 'giang-vien',
    augustinoSlug: 'sach-giang-vien',
    code: 'Gv',
    name: 'Sách Giảng Viên',
    shortName: 'Giảng Viên',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 12,
    summary: 'Suy tư về sự phù vân của trần thế và giá trị đích thực duy nhất là kính sợ Thiên Chúa.',
    onlineUrl: 'https://augustino.net/sach-giang-vien',
    iframeUrl: 'https://augustino.net/sach-giang-vien'
  },
  {
    id: 'diem-ca',
    augustinoSlug: 'sach-diem-ca',
    code: 'Dc',
    name: 'Sách Diễm Ca',
    shortName: 'Diễm Ca',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 8,
    summary: 'Khúc ca tình yêu tuyệt mỹ biểu trưng cho tình yêu giao ước giữa Thiên Chúa và Dân Người.',
    onlineUrl: 'https://augustino.net/sach-diem-ca',
    iframeUrl: 'https://augustino.net/sach-diem-ca'
  },
  {
    id: 'khon-ngoan',
    augustinoSlug: 'sach-khon-ngoan',
    code: 'Kn',
    name: 'Sách Khôn Ngoan',
    shortName: 'Khôn Ngoan',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 19,
    summary: 'Đức Khôn Ngoan của Thiên Chúa ban sự sống đời đời và phần thưởng cho người công chính.',
    onlineUrl: 'https://augustino.net/sach-khon-ngoan',
    iframeUrl: 'https://augustino.net/sach-khon-ngoan'
  },
  {
    id: 'huan-ca',
    augustinoSlug: 'sach-huan-ca',
    code: 'Hc',
    name: 'Sách Huấn Ca',
    shortName: 'Huấn Ca',
    testament: 'old',
    group: 'wisdom',
    groupLabel: 'Giáo Huấn & Thi Văn',
    totalChapters: 51,
    summary: 'Bộ giáo huấn luân lý thực tiễn vĩ đại về tình bạn, gia đình, xã hội và tôn thờ Thiên Chúa.',
    onlineUrl: 'https://augustino.net/sach-huan-ca',
    iframeUrl: 'https://augustino.net/sach-huan-ca'
  },

  // 4. Các Sách Ngôn Sứ (18 Sách)
  {
    id: 'ngon-su-i-sai-a',
    augustinoSlug: 'sach-ngon-su-i-sai-a',
    code: 'Is',
    name: 'Sách Ngôn Sứ I-sai-a',
    shortName: 'I-sai-a',
    testament: 'old',
    group: 'prophets_major',
    groupLabel: 'Sách Ngôn Sứ',
    totalChapters: 66,
    summary: 'Lời tiên tri lừng danh về Đấng Emmanuel, Người Tôi Trung Đau Khổ và Triều Đại Hòa Bình.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-i-sai-a',
    iframeUrl: 'https://augustino.net/sach-ngon-su-i-sai-a'
  },
  {
    id: 'ngon-su-gie-re-mi-a',
    augustinoSlug: 'sach-ngon-su-gie-re-mi-a',
    code: 'Gr',
    name: 'Sách Ngôn Sứ Giê-rê-mi-a',
    shortName: 'Giê-rê-mi-a',
    testament: 'old',
    group: 'prophets_major',
    groupLabel: 'Sách Ngôn Sứ',
    totalChapters: 52,
    summary: 'Ngôn sứ kêu gọi hoán cải, chịu đau khổ vì Lời Chúa và loan báo Giao Ước Mới được khắc vào tâm can.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-gie-re-mi-a',
    iframeUrl: 'https://augustino.net/sach-ngon-su-gie-re-mi-a'
  },
  {
    id: 'ai-ca',
    augustinoSlug: 'sach-ai-ca',
    code: 'Ac',
    name: 'Sách Ai Ca',
    shortName: 'Ai Ca',
    testament: 'old',
    group: 'prophets_major',
    groupLabel: 'Sách Ngôn Sứ',
    totalChapters: 5,
    summary: 'Khúc ca than khóc sự điêu tàn của Giê-ru-sa-lem và niềm cậy trông vào Lòng Thương Xót Chúa.',
    onlineUrl: 'https://augustino.net/sach-ai-ca',
    iframeUrl: 'https://augustino.net/sach-ai-ca'
  },
  {
    id: 'ba-ruc',
    augustinoSlug: 'sach-ba-ruc',
    code: 'Br',
    name: 'Sách Ba-rúc',
    shortName: 'Ba-rúc',
    testament: 'old',
    group: 'prophets_major',
    groupLabel: 'Sách Ngôn Sứ',
    totalChapters: 6,
    summary: 'Lời cầu nguyện sám hối từ chốn lưu đày và lời hứa cứu rỗi vinh hiển cho Si-on.',
    onlineUrl: 'https://augustino.net/sach-ba-ruc',
    iframeUrl: 'https://augustino.net/sach-ba-ruc'
  },
  {
    id: 'ngon-su-e-de-ki-en',
    augustinoSlug: 'sach-ngon-su-e-de-ki-en',
    code: 'Ed',
    name: 'Sách Ngôn Sứ Ê-dê-ki-en',
    shortName: 'Ê-dê-ki-en',
    testament: 'old',
    group: 'prophets_major',
    groupLabel: 'Sách Ngôn Sứ',
    totalChapters: 48,
    summary: 'Thị kiến về Vinh quang Thiên Chúa, cánh đồng hài cốt sống lại và Đền Thờ Mới tràn đầy ân sủng.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-e-de-ki-en',
    iframeUrl: 'https://augustino.net/sach-ngon-su-e-de-ki-en'
  },
  {
    id: 'ngon-su-da-ni-en',
    augustinoSlug: 'sach-ngon-su-da-ni-en',
    code: 'Dn',
    name: 'Sách Ngôn Sứ Đa-ni-en',
    shortName: 'Đa-ni-en',
    testament: 'old',
    group: 'prophets_major',
    groupLabel: 'Sách Ngôn Sứ',
    totalChapters: 14,
    summary: 'Lòng trung thành trong hang sư tử, lò lửa và thị kiến khải huyền về Con Người ngự đến.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-da-ni-en',
    iframeUrl: 'https://augustino.net/sach-ngon-su-da-ni-en'
  },
  {
    id: 'ngon-su-ho-se',
    augustinoSlug: 'sach-ngon-su-ho-se',
    code: 'Hs',
    name: 'Sách Ngôn Sứ Hô-sê',
    shortName: 'Hô-sê',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 14,
    summary: 'Tình yêu thủy chung, tha thứ vô bờ của Thiên Chúa đối với người vợ bội tín Israel.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-ho-se',
    iframeUrl: 'https://augustino.net/sach-ngon-su-ho-se'
  },
  {
    id: 'ngon-su-gio-en',
    augustinoSlug: 'sach-ngon-su-gio-en',
    code: 'Ge',
    name: 'Sách Ngôn Sứ Giô-en',
    shortName: 'Giô-en',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 4,
    summary: 'Ngày của Đức Chúa và lời hứa tuôn đổ Thần Khí trên mọi xác phàm.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-gio-en',
    iframeUrl: 'https://augustino.net/sach-ngon-su-gio-en'
  },
  {
    id: 'ngon-su-a-mot',
    augustinoSlug: 'sach-ngon-su-a-mot',
    code: 'Am',
    name: 'Sách Ngôn Sứ A-mốt',
    shortName: 'A-mốt',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 9,
    summary: 'Tiếng thét công bằng xã hội bênh vực người nghèo hèn trước những kẻ bóc lột xa hoa.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-a-mot',
    iframeUrl: 'https://augustino.net/sach-ngon-su-a-mot'
  },
  {
    id: 'ngon-su-o-va-di-a',
    augustinoSlug: 'sach-ngon-su-o-va-di-a',
    code: 'Ov',
    name: 'Sách Ngôn Sứ Ô-va-đi-a',
    shortName: 'Ô-va-đi-a',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 1,
    summary: 'Lời nghiêm phạt Ê-đôm vì phản nghịch và chiến thắng tối hậu của Vương Quyền Thiên Chúa.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-o-va-di-a',
    iframeUrl: 'https://augustino.net/sach-ngon-su-o-va-di-a'
  },
  {
    id: 'ngon-su-gio-na',
    augustinoSlug: 'sach-ngon-su-gio-na',
    code: 'Gn',
    name: 'Sách Ngôn Sứ Giô-na',
    shortName: 'Giô-na',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 4,
    summary: 'Ngôn sứ trong bụng cá 3 ngày đêm và lòng thương xót của Chúa dành cho dân thành Ni-ni-vê sám hối.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-gio-na',
    iframeUrl: 'https://augustino.net/sach-ngon-su-gio-na'
  },
  {
    id: 'ngon-su-mi-kha',
    augustinoSlug: 'sach-ngon-su-mi-kha',
    code: 'Mk',
    name: 'Sách Ngôn Sứ Mi-kha',
    shortName: 'Mi-kha',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 7,
    summary: 'Lời tiên tri về Đấng Cứu Độ sẽ sinh ra tại Bê-lem Ép-ra-tha nhỏ bé.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-mi-kha',
    iframeUrl: 'https://augustino.net/sach-ngon-su-mi-kha'
  },
  {
    id: 'ngon-su-na-khum',
    augustinoSlug: 'sach-ngon-su-na-khum',
    code: 'Nk',
    name: 'Sách Ngôn Sứ Na-khum',
    shortName: 'Na-khum',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 3,
    summary: 'Sự sụp đổ của đế quốc tàn bạo Át-sua và sự an ủi cho Dân Thánh.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-na-khum',
    iframeUrl: 'https://augustino.net/sach-ngon-su-na-khum'
  },
  {
    id: 'ngon-su-kha-ba-cuc',
    augustinoSlug: 'sach-ngon-su-kha-ba-cuc',
    code: 'Kbc',
    name: 'Sách Ngôn Sứ Kha-ba-cúc',
    shortName: 'Kha-ba-cúc',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 3,
    summary: 'Lời chất vấn Thiên Chúa về sự dữ và lời tuyên tín: "Người công chính sẽ sống nhờ đức tin".',
    onlineUrl: 'https://augustino.net/sach-ngon-su-kha-ba-cuc',
    iframeUrl: 'https://augustino.net/sach-ngon-su-kha-ba-cuc'
  },
  {
    id: 'ngon-su-xo-pho-ni-a',
    augustinoSlug: 'sach-ngon-su-xo-pho-ni-a',
    code: 'Xp',
    name: 'Sách Ngôn Sứ Xô-phô-ni-a',
    shortName: 'Xô-phô-ni-a',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 3,
    summary: 'Ngày Phán Xét của Đức Chúa và niềm vui cứu rỗi của nhóm "người nghèo khó của Thiên Chúa" (Anawim).',
    onlineUrl: 'https://augustino.net/sach-ngon-su-xo-pho-ni-a',
    iframeUrl: 'https://augustino.net/sach-ngon-su-xo-pho-ni-a'
  },
  {
    id: 'ngon-su-khac-gai',
    augustinoSlug: 'sach-ngon-su-khac-gai',
    code: 'Khg',
    name: 'Sách Ngôn Sứ Khác-gai',
    shortName: 'Khác-gai',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 2,
    summary: 'Kêu gọi dân chúng tái thiết Đền Thờ sau lưu đày để đón nhận muôn phúc lành.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-khac-gai',
    iframeUrl: 'https://augustino.net/sach-ngon-su-khac-gai'
  },
  {
    id: 'ngon-su-da-ca-ri-a',
    augustinoSlug: 'sach-ngon-su-da-ca-ri-a',
    code: 'Dcr',
    name: 'Sách Ngôn Sứ Da-ca-ri-a',
    shortName: 'Da-ca-ri-a',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 14,
    summary: 'Các thị kiến khải huyền và lời tiên báo Vua Mêsia khiêm nhu cỡi trên lưng lừa vào Giê-ru-sa-lem.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-da-ca-ri-a',
    iframeUrl: 'https://augustino.net/sach-ngon-su-da-ca-ri-a'
  },
  {
    id: 'ngon-su-ma-la-khi',
    augustinoSlug: 'sach-ngon-su-ma-la-khi',
    code: 'Ml',
    name: 'Sách Ngôn Sứ Ma-la-khi',
    shortName: 'Ma-la-khi',
    testament: 'old',
    group: 'prophets_minor',
    groupLabel: 'Tiểu Ngôn Sứ',
    totalChapters: 3,
    summary: 'Cuốn sách khép lại Cựu Ước: Tiên báo Sứ giả dọn đường (Gioan Tẩy Giả) trước Ngày Chúa Quang Lâm.',
    onlineUrl: 'https://augustino.net/sach-ngon-su-ma-la-khi',
    iframeUrl: 'https://augustino.net/sach-ngon-su-ma-la-khi'
  },

  // =========================================================================
  // II. TÂN ƯỚC (27 SÁCH)
  // =========================================================================

  // 1. Bốn Tin Mừng (Phúc Âm)
  {
    id: 'tin-mung-mat-theu',
    augustinoSlug: 'tin-mung-theo-thanh-mat-theu',
    code: 'Mt',
    name: 'Tin Mừng Theo Thánh Mát-thêu',
    shortName: 'Mát-thêu',
    testament: 'new',
    group: 'gospels',
    groupLabel: 'Bốn Tin Mừng (Phúc Âm)',
    totalChapters: 28,
    summary: 'Đức Giêsu Kitô là Đấng Mêsia hoàn tất mọi lời tiên tri Cựu Ước, Bài giảng trên núi (Bát Phúc) và Lệnh truyền truyền giáo toàn cầu.',
    onlineUrl: 'https://augustino.net/tin-mung-theo-thanh-mat-theu',
    iframeUrl: 'https://augustino.net/tin-mung-theo-thanh-mat-theu'
  },
  {
    id: 'tin-mung-mac-co',
    augustinoSlug: 'tin-mung-theo-thanh-mac-co',
    code: 'Mc',
    name: 'Tin Mừng Theo Thánh Mác-cô',
    shortName: 'Mác-cô',
    testament: 'new',
    group: 'gospels',
    groupLabel: 'Bốn Tin Mừng (Phúc Âm)',
    totalChapters: 16,
    summary: 'Tin Mừng tiên khởi: Đức Giêsu là Con Thiên Chúa hành động uy quyền, chữa lành, trừ quỷ và hiến mạng sống làm giá chuộc muôn người.',
    onlineUrl: 'https://augustino.net/tin-mung-theo-thanh-mac-co',
    iframeUrl: 'https://augustino.net/tin-mung-theo-thanh-mac-co'
  },
  {
    id: 'tin-mung-lu-ca',
    augustinoSlug: 'tin-mung-theo-thanh-lu-ca',
    code: 'Lc',
    name: 'Tin Mừng Theo Thánh Lu-ca',
    shortName: 'Lu-ca',
    testament: 'new',
    group: 'gospels',
    groupLabel: 'Bốn Tin Mừng (Phúc Âm)',
    totalChapters: 24,
    summary: 'Tin Mừng Lòng Thương Xót: Dụ ngôn Người Con Hoang Đàng, Người Samari Nhân Hậu, Giáng Sinh Bêlem và ơn cứu độ phổ quát.',
    onlineUrl: 'https://augustino.net/tin-mung-theo-thanh-lu-ca',
    iframeUrl: 'https://augustino.net/tin-mung-theo-thanh-lu-ca'
  },
  {
    id: 'tin-mung-gio-an',
    augustinoSlug: 'tin-mung-theo-thanh-gio-an',
    code: 'Ga',
    name: 'Tin Mừng Theo Thánh Gio-an',
    shortName: 'Gio-an',
    testament: 'new',
    group: 'gospels',
    groupLabel: 'Bốn Tin Mừng (Phúc Âm)',
    totalChapters: 21,
    summary: 'Tin Mừng Thần Học: Ngôi Lời đã làm người, 7 dấu lạ vinh hiển, Bánh Hằng Sống, Mục Tử Nhân Lành và Mệnh lệnh Yêu Thương.',
    onlineUrl: 'https://augustino.net/tin-mung-theo-thanh-gio-an',
    iframeUrl: 'https://augustino.net/tin-mung-theo-thanh-gio-an'
  },

  // 2. Lịch Sử Hội Thánh
  {
    id: 'cong-vu-tong-do',
    augustinoSlug: 'sach-cong-vu-tong-do',
    code: 'Cv',
    name: 'Sách Công Vụ Tông Đồ',
    shortName: 'Công Vụ',
    testament: 'new',
    group: 'acts',
    groupLabel: 'Lịch Sử Hội Thánh',
    totalChapters: 28,
    summary: 'Lễ Hiện Xuống, hoạt động của Chúa Thánh Thần qua Thánh Phêrô & Thánh Phaolô, khai sinh Giáo Hội tiên khởi và lan rộng đến Rôma.',
    onlineUrl: 'https://augustino.net/sach-cong-vu-tong-do',
    iframeUrl: 'https://augustino.net/sach-cong-vu-tong-do'
  },

  // 3. Thư Thánh Phaolô (14 Thư)
  {
    id: 'thu-ro-ma',
    augustinoSlug: 'thu-gui-tin-huu-ro-ma',
    code: 'Rm',
    name: 'Thư Gửi Tín Hữu Rô-ma',
    shortName: 'Rô-ma',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 16,
    summary: 'Tuyệt tác thần học của Phaolô: Sự công chính hóa nhờ đức tin vào Đức Kitô, ân sủng cứu chuộc và đời sống mới trong Thánh Thần.',
    onlineUrl: 'https://augustino.net/thu-gui-tin-huu-ro-ma',
    iframeUrl: 'https://augustino.net/thu-gui-tin-huu-ro-ma'
  },
  {
    id: '1-co-rin-to',
    augustinoSlug: 'thu-1-gui-tin-huu-co-rin-to',
    code: '1Cr',
    name: 'Thư 1 Gửi Tín Hữu Cô-rin-tô',
    shortName: '1 Cô-rin-tô',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 16,
    summary: 'Giải quyết các chia rẽ cộng đoàn, Bí tích Thánh Thể, Bài ca Đức Ái trác tuyệt (Chương 13) và giáo lý Phục Sinh.',
    onlineUrl: 'https://augustino.net/thu-1-gui-tin-huu-co-rin-to',
    iframeUrl: 'https://augustino.net/thu-1-gui-tin-huu-co-rin-to'
  },
  {
    id: '2-co-rin-to',
    augustinoSlug: 'thu-2-gui-tin-huu-co-rin-to',
    code: '2Cr',
    name: 'Thư 2 Gửi Tín Hữu Cô-rin-tô',
    shortName: '2 Cô-rin-tô',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 13,
    summary: 'Tâm tình chức vụ tông đồ: "Ơn Ta đủ cho con, vì sức mạnh của Ta được biểu lộ trọn vẹn trong sự yếu đuối".',
    onlineUrl: 'https://augustino.net/thu-2-gui-tin-huu-co-rin-to',
    iframeUrl: 'https://augustino.net/thu-2-gui-tin-huu-co-rin-to'
  },
  {
    id: 'ga-lat',
    augustinoSlug: 'thu-gui-tin-huu-ga-lat',
    code: 'Gl',
    name: 'Thư Gửi Tín Hữu Ga-lát',
    shortName: 'Ga-lát',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 6,
    summary: 'Bản tuyên ngôn tự do Kitô giáo: Không còn nô lệ Lề Luật nhưng được tự do trong Thần Khí của tình yêu.',
    onlineUrl: 'https://augustino.net/thu-gui-tin-huu-ga-lat',
    iframeUrl: 'https://augustino.net/thu-gui-tin-huu-ga-lat'
  },
  {
    id: 'e-phe-xo',
    augustinoSlug: 'thu-gui-tin-huu-e-phe-xo',
    code: 'Ep',
    name: 'Thư Gửi Tín Hữu Ê-phê-xô',
    shortName: 'Ê-phê-xô',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 6,
    summary: 'Mầu nhiệm Hội Thánh là Thân Thể Mầu Nhiệm của Đức Kitô và khí giới thiêng liêng chống lại sự dữ.',
    onlineUrl: 'https://augustino.net/thu-gui-tin-huu-e-phe-xo',
    iframeUrl: 'https://augustino.net/thu-gui-tin-huu-e-phe-xo'
  },
  {
    id: 'phi-lip-phe',
    augustinoSlug: 'thu-gui-tin-huu-phi-lip-phe',
    code: 'Pl',
    name: 'Thư Gửi Tín Hữu Phi-líp-phê',
    shortName: 'Phi-líp-phê',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 4,
    summary: 'Bức thư của niềm vui: Thánh thi tụng ca Đức Kitô tự hủy (Kenosis) và "Tôi làm được mọi sự nhờ Đấng ban sức mạnh cho tôi".',
    onlineUrl: 'https://augustino.net/thu-gui-tin-huu-phi-lip-phe',
    iframeUrl: 'https://augustino.net/thu-gui-tin-huu-phi-lip-phe'
  },
  {
    id: 'co-lo-xe',
    augustinoSlug: 'thu-gui-tin-huu-co-lo-xe',
    code: 'Cl',
    name: 'Thư Gửi Tín Hữu Cô-lô-xê',
    shortName: 'Cô-lô-xê',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 4,
    summary: 'Địa vị tối cao tuyệt đối của Đức Kitô là Đầu của Hội Thánh và Trưởng Tử mọi loài thụ tạo.',
    onlineUrl: 'https://augustino.net/thu-gui-tin-huu-co-lo-xe',
    iframeUrl: 'https://augustino.net/thu-gui-tin-huu-co-lo-xe'
  },
  {
    id: '1-the-xa-lo-ni-ca',
    augustinoSlug: 'thu-1-gui-tin-huu-the-xa-lo-ni-ca',
    code: '1Ts',
    name: 'Thư 1 Gửi Tín Hữu Thê-xa-lô-ni-ca',
    shortName: '1 Thê-xa-lô-ni-ca',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 5,
    summary: 'Văn kiện Tân Ước cổ nhất: Niềm hy vọng ngày Chúa quang lâm và lời mời gọi sống thánh thiện, tỉnh thức.',
    onlineUrl: 'https://augustino.net/thu-1-gui-tin-huu-the-xa-lo-ni-ca',
    iframeUrl: 'https://augustino.net/thu-1-gui-tin-huu-the-xa-lo-ni-ca'
  },
  {
    id: '2-the-xa-lo-ni-ca',
    augustinoSlug: 'thu-2-gui-tin-huu-the-xa-lo-ni-ca',
    code: '2Ts',
    name: 'Thư 2 Gửi Tín Hữu Thê-xa-lô-ni-ca',
    shortName: '2 Thê-xa-lô-ni-ca',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 3,
    summary: 'Kiên trì làm việc và giữ vững truyền thống đức tin trước những lừa dối về ngày tận thế.',
    onlineUrl: 'https://augustino.net/thu-2-gui-tin-huu-the-xa-lo-ni-ca',
    iframeUrl: 'https://augustino.net/thu-2-gui-tin-huu-the-xa-lo-ni-ca'
  },
  {
    id: '1-ti-mo-the',
    augustinoSlug: 'thu-1-gui-ong-ti-mo-the',
    code: '1Tm',
    name: 'Thư 1 Gửi Ông Ti-mô-thê',
    shortName: '1 Ti-mô-thê',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Mục Vụ',
    totalChapters: 6,
    summary: 'Chỉ dẫn mục vụ tổ chức cộng đoàn, tiêu chuẩn người lãnh đạo (giám mục, phó tế) và chiến đấu dũng cảm vì đức tin.',
    onlineUrl: 'https://augustino.net/thu-1-gui-ong-ti-mo-the',
    iframeUrl: 'https://augustino.net/thu-1-gui-ong-ti-mo-the'
  },
  {
    id: '2-ti-mo-the',
    augustinoSlug: 'thu-2-gui-ong-ti-mo-the',
    code: '2Tm',
    name: 'Thư 2 Gửi Ông Ti-mô-thê',
    shortName: '2 Ti-mô-thê',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Mục Vụ',
    totalChapters: 4,
    summary: 'Lời trăn trối xúc động của Thánh Phaolô trước khi tử đạo tại Rôma: "Tôi đã chiến đấu trong trận chiến cao đẹp, đã chạy hết chặng đường, đã giữ vững đức tin".',
    onlineUrl: 'https://augustino.net/thu-2-gui-ong-ti-mo-the',
    iframeUrl: 'https://augustino.net/thu-2-gui-ong-ti-mo-the'
  },
  {
    id: 'ti-to',
    augustinoSlug: 'thu-gui-ong-ti-to',
    code: 'Tt',
    name: 'Thư Gửi Ông Ti-tô',
    shortName: 'Ti-tô',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Mục Vụ',
    totalChapters: 3,
    summary: 'Thiết lập trật tự giáo hội tại đảo đảo Cơ-rê-ta và giảng dạy đạo lý lành mạnh.',
    onlineUrl: 'https://augustino.net/thu-gui-ong-ti-to',
    iframeUrl: 'https://augustino.net/thu-gui-ong-ti-to'
  },
  {
    id: 'phi-le-mon',
    augustinoSlug: 'thu-gui-ong-phi-le-mon',
    code: 'Plm',
    name: 'Thư Gửi Ông Phi-lê-môn',
    shortName: 'Phi-lê-môn',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 1,
    summary: 'Bài học tha thứ và đón nhận người nô lệ Ô-nê-xi-mô như một người anh em yêu quý trong Chúa.',
    onlineUrl: 'https://augustino.net/thu-gui-ong-phi-le-mon',
    iframeUrl: 'https://augustino.net/thu-gui-ong-phi-le-mon'
  },
  {
    id: 'do-thai',
    augustinoSlug: 'thu-gui-tin-huu-do-thai',
    code: 'Dt',
    name: 'Thư Gửi Tín Hữu Do-thái',
    shortName: 'Do-thái',
    testament: 'new',
    group: 'pauline',
    groupLabel: 'Thư Thánh Phaolô',
    totalChapters: 13,
    summary: 'Đức Giêsu là Thượng Tế Tối Cao duy nhất theo phẩm trật Men-ki-xê-đê, hiến tế trọn vẹn xóa bỏ mọi hy lễ cũ.',
    onlineUrl: 'https://augustino.net/thu-gui-tin-huu-do-thai',
    iframeUrl: 'https://augustino.net/thu-gui-tin-huu-do-thai'
  },

  // 4. Thư Chung Tông Đồ (7 Thư)
  {
    id: 'gia-co-be',
    augustinoSlug: 'thu-cua-thanh-gia-co-be',
    code: 'Gc',
    name: 'Thư Của Thánh Gia-cô-bê',
    shortName: 'Gia-cô-bê',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 5,
    summary: 'Đức tin không có hành động là đức tin chết: Thực hành bác ái, kiềm chế lời nói và cầu nguyện chữa lành.',
    onlineUrl: 'https://augustino.net/thu-cua-thanh-gia-co-be',
    iframeUrl: 'https://augustino.net/thu-cua-thanh-gia-co-be'
  },
  {
    id: '1-phe-ro',
    augustinoSlug: 'thu-1-cua-thanh-phe-ro',
    code: '1Pr',
    name: 'Thư 1 Của Thánh Phê-rô',
    shortName: '1 Phê-rô',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 5,
    summary: 'Khích lệ các tín hữu chịu bách hại, kiên vững trong niềm hy vọng và trở thành "dân riêng, hàng tư tế vương giả".',
    onlineUrl: 'https://augustino.net/thu-1-cua-thanh-phe-ro',
    iframeUrl: 'https://augustino.net/thu-1-cua-thanh-phe-ro'
  },
  {
    id: '2-phe-ro',
    augustinoSlug: 'thu-2-cua-thanh-phe-ro',
    code: '2Pr',
    name: 'Thư 2 Của Thánh Phê-rô',
    shortName: '2 Phê-rô',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 3,
    summary: 'Cảnh giác trước các ngôn sứ giả và lời nhắc nhở: "Đối với Chúa, một ngày như thể ngàn năm, ngàn năm như thể một ngày".',
    onlineUrl: 'https://augustino.net/thu-2-cua-thanh-phe-ro',
    iframeUrl: 'https://augustino.net/thu-2-cua-thanh-phe-ro'
  },
  {
    id: '1-gio-an',
    augustinoSlug: 'thu-1-cua-thanh-gio-an',
    code: '1Ga',
    name: 'Thư 1 Của Thánh Gio-an',
    shortName: '1 Gio-an',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 5,
    summary: 'Thiên Chúa là Tình Yêu (Deus Caritas Est): Ai yêu thương thì ở trong Thiên Chúa và Thiên Chúa ở trong người ấy.',
    onlineUrl: 'https://augustino.net/thu-1-cua-thanh-gio-an',
    iframeUrl: 'https://augustino.net/thu-1-cua-thanh-gio-an'
  },
  {
    id: '2-gio-an',
    augustinoSlug: 'thu-2-cua-thanh-gio-an',
    code: '2Ga',
    name: 'Thư 2 Của Thánh Gio-an',
    shortName: '2 Gio-an',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 1,
    summary: 'Sống trong Chân Lý và Tình Yêu, cảnh giác với những kẻ chối bỏ Đức Kitô đã đến trong xác phàm.',
    onlineUrl: 'https://augustino.net/thu-2-cua-thanh-gio-an',
    iframeUrl: 'https://augustino.net/thu-2-cua-thanh-gio-an'
  },
  {
    id: '3-gio-an',
    augustinoSlug: 'thu-3-cua-thanh-gio-an',
    code: '3Ga',
    name: 'Thư 3 Của Thánh Gio-an',
    shortName: '3 Gio-an',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 1,
    summary: 'Khen ngợi lòng hiếu khách và sự cộng tác nhiệt thành của ông Gai-út trong sứ vụ truyền giáo.',
    onlineUrl: 'https://augustino.net/thu-3-cua-thanh-gio-an',
    iframeUrl: 'https://augustino.net/thu-3-cua-thanh-gio-an'
  },
  {
    id: 'giu-da',
    augustinoSlug: 'thu-cua-thanh-giu-da',
    code: 'Gd',
    name: 'Thư Của Thánh Giu-đa',
    shortName: 'Giu-đa',
    testament: 'new',
    group: 'catholic_letters',
    groupLabel: 'Thư Chung Tông Đồ',
    totalChapters: 1,
    summary: 'Chiến đấu bảo vệ đức tin duy nhất đã được truyền lại cho các thánh.',
    onlineUrl: 'https://augustino.net/thu-cua-thanh-giu-da',
    iframeUrl: 'https://augustino.net/thu-cua-thanh-giu-da'
  },

  // 5. Ngôn Sứ Tân Ước
  {
    id: 'khai-huyen',
    augustinoSlug: 'sach-khai-huyen',
    code: 'Kh',
    name: 'Sách Khải Huyền',
    shortName: 'Khải Huyền',
    testament: 'new',
    group: 'revelation',
    groupLabel: 'Ngôn Sứ Tân Ước',
    totalChapters: 22,
    summary: 'Khải tượng vinh quang của Thánh Gioan: Con Chiên khải hoàn, sự chiến thắng tối hậu của Thiên Chúa, Trời Mới Đất Mới và Giê-ru-sa-lem Thiên Quốc.',
    onlineUrl: 'https://augustino.net/sach-khai-huyen',
    iframeUrl: 'https://augustino.net/sach-khai-huyen'
  }
];

export const BIBLE_SUMMARY_INFO = {
  title: 'Kinh Thánh Trọn Bộ (Cựu Ước & Tân Ước)',
  subTitle: '73 Sách Lời Chúa • Bản Dịch KTCGKPV & Hội Đồng Giám Mục Việt Nam',
  author: 'Nhóm Phiên Dịch Các Giờ Kinh Phụng Vụ (KTCGKPV)',
  totalBooks: 73,
  oldTestamentBooksCount: 46,
  newTestamentBooksCount: 27,
  totalChapters: 1334,
  description: 'Trọn bộ 73 cuốn Sách Thánh Cựu Ước và Tân Ước được Hội Đồng Giám Mục Việt Nam phê chuẩn sử dụng chính thức trong Phụng vụ Thánh Lễ và đời sống cầu nguyện của toàn thể người tín hữu Công giáo Việt Nam.',
  sourceWebsite: 'https://augustino.net/kinh-thanh',
  officialOnlineUrl: 'https://augustino.net/kinh-thanh',
  officialIframeUrl: 'https://augustino.net/kinh-thanh'
};
